// <auto-generated />
namespace StudentInformationSystemWebApp.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.0-20911")]
    public sealed partial class StudentCourseModelAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StudentCourseModelAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202110301512002_StudentCourseModelAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
